#!/bin/bash


if [ -z "$1" ]
then
    echo "Error: Need to provide project name as argument"
    exit 1
fi

PROJECT_NAME=$1

echo "Running xUnique..."
bash -l -c "python ./scripts/xUnique.py $PROJECT_NAME.xcodeproj/ > /dev/null"
